module.exports = [
	{ category: 'languages', value: 1, name: 'Python' },
	{ category: 'languages', value: 1, name: 'C' },
	{ category: 'languages', value: 1, name: 'Java' },
	{ category: 'languages', value: 1, name: 'C++' },
	{ category: 'languages', value: 1, name: 'C#' },
	{ category: 'languages', value: 3, name: 'JavaScript' },
	{ category: 'languages', value: 1, name: 'PHP' },
	{ category: 'languages', value: 2, name: 'Go' },
	{ category: 'languages', value: 2, name: 'Swift/Objective-C' },
	{ category: 'languages', value: 1, name: 'Scala' },
	{ category: 'languages', value: 1, name: 'Ruby' },
	{ category: 'languages', value: 2, name: 'Web Assembly' },
	{ category: 'web_technologies', value: 1, name: 'HTML' },
	{ category: 'web_technologies', value: 1, name: 'CSS' },
	{ category: 'web_technologies', value: 5, name: 'React' },
	{ category: 'web_technologies', value: 4, name: 'Node/Express' },
	{ category: 'web_technologies', value: 3, name: 'Angular' },
	{ category: 'web_technologies', value: 3, name: 'Vue' },
	{ category: 'web_technologies', value: 1, name: 'Larvel/Symfony' },
	{ category: 'web_technologies', value: 1, name: 'Ruby on Rails' },
	{ category: 'web_technologies', value: 1, name: 'ASP.NET' },
	{ category: 'web_technologies', value: 1, name: 'Django' },
	{ category: 'web_technologies', value: 1, name: 'Flask' },
	{ category: 'web_technologies', value: 1, name: 'Meteor' },
	{ category: 'web_technologies', value: 1, name: 'Ember' },
	{ category: 'web_technologies', value: 1, name: 'Backbone' },
	{ category: 'web_technologies', value: 1, name: 'Wordpress' },
	{ category: 'databases', value: 1, name: 'MySQL' },
	{ category: 'databases', value: 1, name: 'SQLite' },
	{ category: 'databases', value: 2, name: 'MongoDB' },
	{ category: 'databases', value: 2, name: 'Redis' },
	{ category: 'databases', value: 2, name: 'PostgreSQL' },
	{ category: 'databases', value: 1, name: 'Oracle SQL' },
	{ category: 'databases', value: 1, name: 'Cassandra' },
	{ category: 'databases', value: 1, name: 'MariaDB' },
	{ category: 'databases', value: 1, name: 'CouchDB' },
	{ category: 'databases', value: 2, name: 'Neo4j' },
	{ category: 'databases', value: 2, name: 'Elasticsearch' },
	{ category: 'databases', value: 1, name: 'Amazon SimpleDB' },
	{ category: 'databases', value: 1, name: 'Firebase' },
	{ category: 'databases', value: 1, name: 'Apache Spark' },
	{ category: 'databases', value: 1, name: 'Hadoop' },
	{ category: 'databases', value: 1, name: 'CockroachDB' },
	{ category: 'deployment', value: 1, name: 'Google Cloud' },
	{ category: 'deployment', value: 1, name: 'Azure' },
	{ category: 'deployment', value: 1, name: 'AWS' },
	{ category: 'deployment', value: 1, name: 'Heroku' },
	{ category: 'deployment', value: 1, name: 'Kubernetes' },
	{ category: 'deployment', value: 1, name: 'Apache' },
	{ category: 'deployment', value: 1, name: 'Docker' },
	{ category: 'deployment', value: 1, name: 'Nginx' },

];